name = "smsbomber"
main = "build/worker/shim.mjs"
compatibility_date = "2026-05-09"
[build]
command = "worker-build --release"

[build.upload]
format = "modules"
dir = "build/worker"
main = "./shim.mjs"
